In [1]:
import numpy as np

# Marks array (5 students × 3 subjects)
marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 45],
    [65, 70, 75]
])

print(marks)


[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 45]
 [65 70 75]]


In [2]:
print(marks.shape)


(5, 3)


In [3]:
print(marks.size)


15


In [4]:
print(marks.dtype)


int64


In [5]:
print(marks[1])


[45 60 55]


In [6]:
print(marks[:, 2])


[90 55 95 45 75]


In [7]:
print(marks[0, 1])


85
