In [8]:
import numpy as np

# Daily sales data
daily_sales = np.array([
    [10, 15, 8, 12],   # Headphones
    [5, 7, 4, 6],      # Smartwatch
    [2, 3, 2, 4]       # Speakers
])

print(daily_sales)



[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


In [9]:
bonus_sales = daily_sales + 2
print("Sales after bonus:\n", bonus_sales)



Sales after bonus:
 [[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [10]:
# Cost price of each product
cost_price = np.array([1000, 2000, 1500])

# Multiply sales with cost price
revenue = daily_sales * cost_price.reshape(3, 1)

print("Revenue matrix:\n", revenue)

# Total revenue per day
total_revenue = revenue.sum(axis=0)
print("Total revenue per day:\n", total_revenue)


Revenue matrix:
 [[10000 15000  8000 12000]
 [10000 14000  8000 12000]
 [ 3000  4500  3000  6000]]
Total revenue per day:
 [23000 33500 19000 30000]


In [11]:
sqrt_sales = np.sqrt(daily_sales)
print("Square root of sales:\n", sqrt_sales)


Square root of sales:
 [[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]
