In [1]:
import numpy as np

daily_sales = np.array([
    [10, 15, 8, 12],   # Headphones
    [5, 7, 4, 6],      # Smartwatches
    [2, 3, 2, 4]       # Speakers
])


In [2]:
smartwatch_sales = daily_sales[1]
print(smartwatch_sales)


[5 7 4 6]


In [3]:
first_two_days = daily_sales[:, :2]
print(first_two_days)


[[10 15]
 [ 5  7]
 [ 2  3]]


In [4]:
speakers_thursday = daily_sales[2][3]
print(speakers_thursday)


4


In [5]:
sub_array = daily_sales[0:2, 0:2]
print(sub_array)


[[10 15]
 [ 5  7]]
