In [1]:
import numpy as np

daily_sales = np.array([
    [10, 15, 8, 12],
    [5, 7, 4, 6],
    [2, 3, 2, 4]
])


In [2]:
flat_sales = daily_sales.reshape(12)
print(flat_sales)


[10 15  8 12  5  7  4  6  2  3  2  4]


In [3]:
sales_2x6 = daily_sales.reshape(2, 6)
print(sales_2x6)


[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]


In [4]:
discounts = np.linspace(0, 100, 10)
print(discounts)


[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
