In [1]:
import numpy as np

# Marks array (5 students × 3 subjects)
marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 45],
    [65, 70, 75]
])

print(marks)


[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 45]
 [65 70 75]]


In [2]:
print(marks.shape)


(5, 3)


In [3]:
print(marks.size)


15


In [4]:
print(marks.dtype)


int64


In [5]:
print(marks[1])


[45 60 55]


In [6]:
print(marks[:, 2])


[90 55 95 45 75]


In [7]:
print(marks[0, 1])


85


In [8]:
student_avg = np.mean(marks, axis=1)
subject_avg = np.mean(marks, axis=0)

print("Average marks of each student:", student_avg)
print("Average marks of each subject:", subject_avg)


Average marks of each student: [84.33333333 53.33333333 91.66666667 38.33333333 70.        ]
Average marks of each subject: [61.2 69.4 72. ]


In [9]:
student_avg = np.mean(marks, axis=1)
top_students = np.where(student_avg >= 80)

print("Students with average marks >= 80:", top_students[0] + 1)


Students with average marks >= 80: [1 3]


In [10]:
status = np.where(marks >= 50, 1, 0)
print(status)


[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


In [11]:
marks[marks < 40] = 0
print(marks)


[[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40 45]
 [65 70 75]]
