In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
import numpy as np

arr2 = np.array([[1, 2, 3],
                 [2, 4, 3]])

print(arr2)


[[1 2 3]
 [2 4 3]]


Line 1: a = np.zeros((2,3,3))
Creates a box-shaped container (3D array) with dimensions 2×3×3, and fills it completely with zeros.

Line 2: b = np.zeros((2,3,3))
Creates another identical box with the same dimensions, also filled with zeros.

Line 3: c = np.random.rand(2,3,4)
Creates a different-sized box with dimensions 2×3×4, but fills it with random decimal numbers between 0 and 1.

Line 4: print(a,b,c)
Displays all three boxes and their contents on the screen.

In [5]:
a = np.zeros((2,3,3))
b = np.zeros((2,3,3))
c = np.random.rand(2,3,4)
print(a,b,c)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] [[[0.22811208 0.35472406 0.76135801 0.70598048]
  [0.77503348 0.09862663 0.72448462 0.7799655 ]
  [0.29368583 0.87271924 0.32034629 0.63403424]]

 [[0.43275256 0.5410495  0.45606668 0.26793498]
  [0.05547557 0.51362365 0.83772148 0.08279025]
  [0.36990346 0.61027605 0.73088508 0.3192194 ]]]


Think of it like counting with a specific pattern:

First number (0): Start counting from 0
Second number (10): Stop before you reach 10
Third number (2): Skip by 2 each time
Result: [0, 2, 4, 6, 8]

Like counting by 2s:

Start at 0
Jump to 2
Jump to 4
Jump to 6
Jump to 8
Stop (because next would be 10, and we stop before reaching 10)

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

This creates a list of exactly 10 evenly spaced numbers between 0 and 5.

First number (0): Start at 0
Second number (5): End at 5 (inclusive)
Third number (10): Create exactly 10 numbers
Result: [0.   0.55555556  1.11111111  1.66666667  2.22222222  2.77777778  3.33333333  3.88888889  4.44444444  5. ]

In [7]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

arr = np.array([[1,2,3] , [4,5,6]]) creates a 2×3 table:

Then the print statements show information about it:

print(arr.ndim) → 2

ndim = "number of dimensions"
This is a 2D array (like a table with rows and columns)
print(arr.shape) → (2, 3)

shape = "dimensions of the array"
2 rows and 3 columns
print(arr.size) → 6

size = "total number of elements"
2 rows × 3 columns = 6 total items
print(arr.dtype) → int64 (or similar)

dtype = "data type of the elements"
The numbers are stored as integers (whole numbers)

In [8]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


Type Conversion

In [9]:
arr = np.array([1,2,2.5,3.7])
arr_int = arr.astype(int)
print(arr_int)

[1 2 2 3]


1D Slicing & Indexing 
This code shows different ways to access elements in an array:

Array: [10, 20, 30, 40] (at positions 0, 1, 2, 3)

print(arr[0]) → 10

Gets the first element (position 0)
In programming, counting starts at 0, not 1

print(arr[-1]) → 40
Gets the last element using negative indexing
-1 means "the last one", -2 means "second to last", etc.
print(arr[1:3]) → [20, 30]

Slicing: gets elements from position 1 to 2 (not including 3)
Format: [start:stop] (stop is exclusive)
print(arr[:2]) → [10, 20]

Gets elements from the beginning up to position 2 (not including 2)
Empty before : means "start from the beginning"

print(arr[::2]) → [10, 30]
Gets every 2nd element starting from the beginning
Format: [start:stop:step]
Empty start and stop means "all elements", 2 means "every 2nd"
Think of it like picking items from a list:

arr[0] = "give me item at spot 0"
arr[-1] = "give me the last item"
arr[1:3] = "give me items from spot 1 to 2"
arr[:2] = "give me items from the start up to spot 2"
arr[::2] = "give me every other item"

In [10]:
arr = np.array([10,20,30,40])
print(arr[0]) #Indexing
print(arr[-1])

print(arr[1:3])
print(arr[:2])
print(arr[::2])

10
40
[20 30]
[10 20]
[10 30]


2D Indexing

This line gets an entire column from the 2D array.

Breaking it down:

mat[:, 1]
: = "all rows"
, = separator between rows and columns
1 = column index 1 (the second column, since counting starts at 0)

In [11]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(mat[0,1])
print(mat[1])
print(mat[:,1])

2
[4 5 6]
[2 5 8]


Dot Copy Function

In [12]:
a = np.array([1,2,3])
b = a.copy() #copy
# b = a This logic is not safe because it will change the original array also
b[0] = 99
print(a)
print(b)

[1 2 3]
[99  2  3]


Basic Array Operation (Vector Power)

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Scalar Operations

In [14]:
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


Unfus (Universal Functions)

In [15]:
arr = np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


In [32]:
#Boolean Indexing

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr[arr > 25])
print(arr>25)

[30 40 50]
[False False  True  True  True]


numPy automatically expands smaller arrays

In [17]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr + 10)

[11 12 13 14]


In [18]:
mat  = np.array([[1,2,3],
                [4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


In [19]:
row = np.array([1,2,3])
print(mat+ row)

[[2 4 6]
 [5 7 9]]


Matrix Multiplication

In [20]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [21]:
print(A.T) #Transpose

[[1 3]
 [2 4]]


Random Module

In [22]:
np.random.rand(3,3)

array([[0.6568874 , 0.27455388, 0.0722466 ],
       [0.17958137, 0.410696  , 0.27620677],
       [0.95701241, 0.24753694, 0.15641621]])

In [23]:
np.random.randint(1,100,10)

array([15, 57, 19,  7, 94, 90, 95, 59, 84, 77], dtype=int32)

Reshaping Arrays

In [25]:
arr = np.arange(12)
print(arr.reshape(3,4))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Axis in NumPy

In [26]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
print(np.sum(arr))

21


In [29]:
print(np.sum(arr,axis = 0)) #column-wise
print(np.sum(arr,axis = 1)) # row-wise

[5 7 9]
[ 6 15]


Where is NumPy

In [30]:
arr = np.array([10,-5,20,-3,15])
result = np.where(arr<0,0,arr)
print(result)

[10  0 20  0 15]


In [31]:
arr = np.array([1,2,3,4,5])
result = np.where(arr%2 != 0, -1, arr)
print(result)

[-1  2 -1  4 -1]


In [34]:
marks  = np.array([45,78,32,90,55])
status = np.where(marks>=50 , 1, 0)
print(status)

[0 1 0 1 1]


In [35]:
data = np.array([10,20,30,40,50])
mean_val = np.mean(data)
result = np.where(data>mean_val , mean_val, data)
print(result)

[10. 20. 30. 30. 30.]


applying(where) condition in 2D array

In [37]:
mat = np.array([
    [10,60,30],
    [00,20,90]
])
result = np.where(mat>=50 ,1,0)
print(result)

[[0 1 0]
 [0 0 1]]
