In [1]:
import numpy as np


In [2]:
predicted_sales = np.random.randint(0, 21, size=(3, 4))
print("Predicted Sales:\n", predicted_sales)


Predicted Sales:
 [[20  9 12  9]
 [ 5  5  3  9]
 [16  9  0 16]]


In [3]:
random_values = np.random.rand(5)
print("Random values:\n", random_values)


Random values:
 [0.68276166 0.74557087 0.48468083 0.18805433 0.23455629]


In [4]:
daily_sales = np.array([
    [10, 15, 8, 12],   # Headphones
    [5, 7, 4, 6],      # Smartwatches
    [2, 3, 2, 4]       # Speakers
])


In [5]:
total_items = np.sum(daily_sales)
print("Total items sold:", total_items)


Total items sold: 78


In [6]:
product_wise_total = np.sum(daily_sales, axis=1)
print("Items sold per product:", product_wise_total)


Items sold per product: [45 22 11]
